---
- name: Install NERDCTL
  unarchive: 
    src: https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}/nerdctl-{{ nerdctl_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create a directories if not exist
  block:
  - name: Create a directory for binaries
    file:
      path: /opt/etcdRAM/bin/
      state: directory
      mode: 0755
  - name: Create a directory for backup
    file:
      path: /var/lib/etcdRAM/etcd
      state: directory
      mode: 0755

- name: Copy files for etcdRAM
  block:
  - name: Copy cronjob file
    copy:
      src: files/files_etcdRAM/etc/cron.d/etcdRAM-etcd
      dest: /etc/cron.d/etcdRAM-etcd
      mode: 0644
  - name: Copy scripts
    copy:
      src: files/files_etcdRAM/opt/etcdRAM/bin/
      dest: /opt/etcdRAM/bin/
      mode: 0755
  - name: Copy kubelet configuration
    copy:
      src: files/files_etcdRAM/usr/lib/systemd/system/kubelet.service.d/
      dest: /usr/lib/systemd/system/kubelet.service.d/
      mode: 0644
    notify: restart daemon-reload

- name: Add a cron file from dir /etc/cron.d
  ansible.builtin.shell: "crontab /etc/cron.d/etcdRAM-etcd"
