{% if cert_manager_type == 'self-signed' %}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
{% else %}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ cert_manager_type }}-issuer"
spec:
  acme:
    # The ACME server URL
    server: {{ acme_server_url }} #https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ acme_email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
{% endif %}  
